version: '3.4'

services:
  pizzerianlab3:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  pizzarestaurant.api.inventory:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  pizzarestaurant.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

